
export const dataExtension = [
    {
        name:'Change Page Name',
        image:'https://mir-s3-cdn-cf.behance.net/project_modules/1400/8e52ba41294625.57a08b6d3a440.png',
        short:'The quickest pair of page names',
        detail:'The quickest pair of page names',
        type:'facebook',
        down:'1.347',
        zip:'pagename',
        youtube:'sdsdsdfsdf',
    },
    {
        name:'Filter group members',
        image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJVpGmYuFW1UFi58bwiQc8OxEaTiWAi2La4Pc0359D8RUcKraerIlJtJGNnMJBgcMACB8&usqp=CAU',
        short:'Quickly filter group members who are dead or inactive',
        detail:'Quickly filter group members who are dead or inactive',
        type:'facebook',
        down:'10.247',
        zip:'group_members',
        youtube:'sdsdsdfsdf',
    },
    {
        name:'Group resistance is warned',
        image:'https://plus24h.com/upload/editor/images/luu-y-khi-dang-bai-tren-group-facebook-1.png',
        short:'Submit a legitimate and prompt request to remove the warning',
        detail:'Submit a legitimate and prompt request to remove the warning',
        type:'facebook',
        down:'542',
        zip:'group_resistance',
        youtube:'sdsdsdfsdf',
    },
    {
        name:'Request identity verification',
        image:'https://minter.io/blog/content/images/2022/08/How-to-get-verified-on-Instagram-post.jpg',
        short:'Submit a legitimate and prompt request to remove the warning',
        detail:'Helps you submit identity verification requests, quickly supported by support',
        type:'facebook',
        down:'7.823',
        zip:'identity_verification',
        youtube:'sdsdsdfsdf',
    },
    {
        name:'Group posts',
        image:'https://www.gotwogether.com/wp-content/uploads/2014/11/Facebook-Group-Featured.jpg',
        short:'Filter and delete posts in your group',
        detail:'Filter and delete posts in your group',
        type:'facebook',
        down:'5.239',
        zip:'group_post',
        youtube:'sdsdsdfsdf',
    },
    {
        name:'Friends on facebook',
        image:'https://i.insider.com/559cf0d8371d22ce178b5b99?width=579&format=jpeg',
        short:'Helps you filter your friend list on Facebook',
        detail:'Helps you filter your friend list on Facebook',
        type:'facebook',
        down:'9.067',
        zip:'friend_facebook',
        youtube:'sdsdsdfsdf',
    }
    ,
    {
        name:'LiveStream on facebook',
        image:'https://static.vecteezy.com/system/resources/previews/009/636/714/non_2x/live-streaming-social-media-free-png.png',
        short:'Follow live stream.enable hidden feature',
        detail:'Follow live stream.enable hidden feature',
        type:'facebook',
        down:'2.907',
        zip:'live_facebook',
        youtube:'sdsdsdfsdf',
    }
    ,
    {
        name:'Messages on facebook',
        image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQukjTeWXroIQaP7tOQTYA-DVFbCYcaGjxg09Y95PVp_g&s',
        short:'Recover previously deleted Facebook messages, and block viewers',
        detail:'Recover previously deleted Facebook messages, and block viewers',
        type:'facebook',
        down:'15.342',
        zip:'message_facebook',
        youtube:'sdsdsdfsdf',
    },
    {
        name:'Raise the Facebook account threshold',
        image:'https://www.premiumseo.co.nz/wp-content/uploads/2022/05/facebook-ads-nz.png',
        short:'Open account threshold limit quickly and most conveniently',
        detail:'Open account threshold limit quickly and most conveniently',
        type:'facebook',
        down:'6.454',
        zip:'threshold_facebook',
        youtube:'sdsdsdfsdf',
    },
    {
        name:'Filter facebook comments',
        image:'https://cdn-icons-png.flaticon.com/512/9358/9358500.png',
        short:'Filter facebook comments',
        detail:'Filter facebook comments',
        type:'facebook',
        down:'2.009',
        zip:'comments_facebook',
        youtube:'sdsdsdfsdf',
    }
] 